name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Inputting "1,2,3,4,5" test
      id: inputting-1-2-3-4-5-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "1,2,3,4,5" test
        setup-command: ''
        command: python3 list_stats/main.py
        input: '1,2,3,4,5'
        expected-output: "^Max: 5\\nMin: 1\\nSum: 15\\nAvg: 3\\.0\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 1
    - name: Inputting "2,2,2,2" test
      id: inputting-2-2-2-2-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "2,2,2,2" test
        setup-command: ''
        command: python3 list_stats/main.py
        input: '2,2,2,2'
        expected-output: "^Max: 2\\nMin: 2\\nSum: 8\\nAvg: 2\\.0\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 2
    - name: Inputting "10,3,8,1" test
      id: inputting-10-3-8-1-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "10,3,8,1" test
        setup-command: ''
        command: python3 list_stats/main.py
        input: '10,3,8,1'
        expected-output: "^Max: 10\\nMin: 1\\nSum: 22\\nAvg: 5\\.5\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 2
    - name: Inputting "-3,-2,-1,0" test
      id: inputting-3-2-1-0-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "-3,-2,-1,0" test
        setup-command: ''
        command: python3 list_stats/main.py
        input: "-3,-2,-1,0"
        expected-output: "^Max: 0\\nMin: -3\\nSum: -6\\nAvg: -1\\.5\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INPUTTING-1-2-3-4-5-TEST_RESULTS: "${{steps.inputting-1-2-3-4-5-test.outputs.result}}"
        INPUTTING-2-2-2-2-TEST_RESULTS: "${{steps.inputting-2-2-2-2-test.outputs.result}}"
        INPUTTING-10-3-8-1-TEST_RESULTS: "${{steps.inputting-10-3-8-1-test.outputs.result}}"
        INPUTTING-3-2-1-0-TEST_RESULTS: "${{steps.inputting-3-2-1-0-test.outputs.result}}"
      with:
        runners: inputting-1-2-3-4-5-test,inputting-2-2-2-2-test,inputting-10-3-8-1-test,inputting-3-2-1-0-test
